### ISSUE TITLE
Link to paper

### ISSUE THREAD

**Issue by ofirkris** [ewrfcas/MAE-FAR#1]
Hi thanks  for publishing - can you share the link for the paper to study your work?
Also when do you plan to upload weights for testing?

Do you believe your method can outperform MAT inpainting on places dataset? have you compared?

**Comment by ewrfcas** [comment]
Hi, our paper will be released soon. The pre-trained weights will be uploaded a bit later.

**Comment by ewrfcas** [comment]
Comparisons between MAT can be found in our Appendix.

**Comment by ofirkris** [comment]
Where can the paper be found?
