### ISSUE TITLE
When do you release the pretrained weight?

### ISSUE THREAD

**Issue by UdonDa** [ewrfcas/MAE-FAR#1]
Hi, @ewrfcas!

I read your insightful paper. I'd like to use your work for my academic research.
So, when do you release other codes and pretrained weights?

**Comment by ewrfcas** [comment]
Thanks for your attention.
We will release codes as fast as possible. For some copyright issues, we cannot release models until the ECCV conference.

**Comment by ewrfcas** [comment]
Hi, we have re-trained and released the full model.
