### ISSUE TITLE
Questions about the weights released

### ISSUE THREAD

**Issue by yqjiang6** [ewrfcas/MAE-FAR#10]
Hi!
Thanks for the weights you released, but I have some questions about this. As you report results on two datasets but only release on weights, I was wondering which dataset is your weights trained on? The places2 or FFHQ? Could you please provide weights trained on both datasets?
Thank you!

**Comment by ewrfcas** [comment]
We use FFHQ and places2 MAE weights respectively for the human face task (FFHQ) and scene inpainting task (Places2).
And we did not train weights on both datasets.

**Comment by yqjiang6** [comment]
Sorry I think I do not fully understand your responds. Do you mean that you only train one model for ACR and use that model in both FFHQ and Places2? As you provide the results on both FFHQ and Places2, there should be two different model weights. Thank you!

**Comment by ewrfcas** [comment]
Sorry for the confusing response. ACR and MAE are trained with two different models for Places2 and FFHQ.
Did you need model (ACR) based on FFHQ?

**Comment by yqjiang6** [comment]
It's better if you could provide the ACR of both FFHQ and Places2. In addition, I want to make sure that whether the results of 256x256 resolution is tested on the model only trained with 256x256 images or on the model fine-tuned on 512x512 images?

**Comment by ewrfcas** [comment]
I am sorry that we could not provide the FFHQ-based ACR now. Because the FFHQ model is trained on old codes, which are not adapted to the released codes. Retraining a new face model based on pre-trained MAE will not cost much time. Maybe we will provide it in the future.

Results of 256 resolution are not finetuned with 512 images.

**Comment by yqjiang6** [comment]
Thanks for your reply! It really helps me a lot.
