### ISSUE TITLE
MAE Eocoder

### ISSUE THREAD

**Issue by soobin419** [ewrfcas/MAE-FAR#14]
Hello,

I have a question regarding the MAE Encoder in your recent paper. 

As far as I understand, the encoder of MAE only takes unmasked patches as input. 
However, looking at the code, it seems that the masked patch is also used for the encoder's attention calculation.
Specifically, it seems that after calculating the attention score using both unmasked and masked patches, masking is applied to the attention score using the yellow area shown in the attached image.

Is it correct in this implementation to allow masked patches to have attention scores as unmasked patches?

For example, if we patch-embed an input image to get 8 patches, and 2 of them are masked, shouldn't MAE's encoder calculate the attention score between the 6 unmasked patches?
However, upon examining the code, it seems that all 8 patches are used to calculate attention scores.

![image](https://user-images.githubusercontent.com/62980764/232775806-30fdb10b-ae4a-42b2-9691-9c55988a7b08.png)

I would appreciate it if you could provide an explanation for this implementation.

Thank you for your time and consideration.

**Comment by ewrfcas** [comment]
Hi, you can refer to the related codes in models_mae.py
https://github.com/ewrfcas/MAE-FAR/blob/f7069dbca046f58ce8008c178db862e18facca5b/MAE/models_mae.py#L192-L210
Masked tokens should be removed before being applied to the MAE encoder.

**Comment by soobin419** [comment]
Oh, thank you.

I think I confused the ACR training phase and the MAE training phase.

**Comment by jackhu-bme** [comment]
> Hi, you can refer to the related codes in models_mae.py
> 
> https://github.com/ewrfcas/MAE-FAR/blob/f7069dbca046f58ce8008c178db862e18facca5b/MAE/models_mae.py#L192-L210
> 
> 
> Masked tokens should be removed before being applied to the MAE encoder.

I am confused for one thing: when training mae, this forward_encoder funtion is used, which is consistent with mae original paer; when accessing the mae feat (training the acr), the forward_encoder_with _mask function is used. When mask is provided, the forward_encoder_with _mask function use both the masked and unmasked tokens, which changes the way attention and score is calculated. Though the original MAE repo does not offer any code of testing with random mask image and random mask ratio, I am curious about the change in the funtion "forward_encoder_with _mask". Will this yield better encoded feature? Will this improve the inpainting process? No explanation is found in the paper.

**Comment by jackhu-bme** [comment]
In the encoder forwarding with mask,this mask_fill influence both the score(for returning the score) and attention(for forwading the feature). In decoder forwarding with mask, only the score is influenced. Again, I wonder why.

**Comment by jackhu-bme** [comment]
Does this implementation follow any repo or is based on any experience?

**Comment by jackhu-bme** [comment]
I see this implementation is interesting after debugging, the mask_fill fill the masked columns in attention map as 0 in the final attention result, making the masked value of v vector not influence the final output after attention block. Will this provide better mae feartures for acr training? Is the visualization result of final mae output after this process available?(What's the difference in visualization if we encode just as the original mae repo)

**Comment by jackhu-bme** [comment]
after my experiements, not much obvious difference. However, the mask ratio of given mask maybe different among different images within a batch image, so this repo's implementation of using all the tokens for encoder is more flexible but consume a little more gpu memory.

**Comment by ewrfcas** [comment]
> after my experiements, not much obvious difference. However, the mask ratio of given mask maybe different among different images within a batch image, so this repo's implementation of using all the tokens for encoder is more flexible but consume a little more gpu memory.


Hi, ```forward_encoder_with_mask``` is used to be compatible for any types of irregular or object-segmentation masking, which is more suitable for the image inpainting. Moreover, during the training, we would further randomly mask the inputs until the masking ratio is up to 75%.

For the ```masked_fill```, it should be used to ensure that only unmasked regions are attended for the feature aggregation, which should be seen as the classical *contextual attention*. It also slightly improves the final results.

**Comment by jackhu-bme** [comment]
Thanks a lot for your detailed clarification !
