### ISSUE TITLE
About resolution

### ISSUE THREAD

**Issue by UdonDa** [ewrfcas/MAE-FAR#15]
Hi, @ewrfcas 

Thank you for providing your nice implementation!
I have a question.

You evaluated your model using a 512x512 resolution. However, you provide only 256x256 weight using a Places dataset.
Why don't you provide 512x512 weights?

**Comment by ewrfcas** [comment]
The released model has been finetuned on 512x512 images.

**Comment by UdonDa** [comment]
The input for MAE  is 256x256, but the rest network is 512x512, right?
Please excuse my lack of understanding.

**Comment by ewrfcas** [comment]
Yes, the feature will be resized as mentioned in the paper.

**Comment by UdonDa** [comment]
I understand your method perfectly. Thank you for explaining to me!!
I can run your code.

Thank you.
