### ISSUE TITLE
problems about testing?

### ISSUE THREAD

**Issue by CodeMadUser** [ewrfcas/MAE-FAR#2]
hello,it's an amazing work.I have some problems about testing:
1\  I use simple_test.ipynb to test,but it has to need two figures,one is GT,another is mask figure, if I only have a picture with mask,what should I do to start the testing?
2\ When I test the single picture,my result is not good,for example:
![image](https://user-images.githubusercontent.com/97572749/198867167-4bd1025b-5c7b-4297-8966-3d152fee4b1c.png)

My folder directory is as follows：
![image](https://user-images.githubusercontent.com/97572749/198867283-8e4cf45a-19bf-4bf6-b068-2acc4fa77715.png)

thank you for your works.looking forward to your replying.

**Comment by ewrfcas** [comment]
Hi, for the first question, you should provide a 0-1 mask for the inpainting. Some GUI can provide such masks.
For the second question, the released model (MAE) only works for the pre-training, so it cannot provide good results with detailed textures. 
You can re-train a new model based on the released MAE following train.py.
The full inpainting model will be released later.

**Comment by CodeMadUser** [comment]
> 

thank you.I will try your suggestions.
