### ISSUE TITLE
Clarification on "TIPS: Now we recommend to use features from layer6 of the MAE instead of layer8 to enjoy superior performance."

### ISSUE THREAD

**Issue by zhou13** [ewrfcas/MAE-FAR#20]
Hi @ewrfcas, First, I'd like to thank you for providing such simple and concise code. Great work on inpainting! I want to get some clarification on your new tips. I cannot find any place where you used layer 8 MAE features in the code. Could you point to me the line? Thank you.

**Comment by ewrfcas** [comment]
Hi, this conclusion is discovered in our subsequent research. So related codes and models have not been updated yet. We recommend using the 6th layer from the pre-trained MAE to train your new model for superior performance.
Here is the figure about the performance of different layers.

![image](https://github.com/ewrfcas/MAE-FAR/assets/12042259/08731dcb-3699-4e0d-b99a-3297a1d66a12)

Your could find that layer 8 slightly outperforms the image output (but the image output is not stable), but layer 6 performs best and is most stable among all features.

**Comment by zhou13** [comment]
Thank you for the input! Just to clarify, the release model is using the "Image" layer as shown in the plot, right?

**Comment by ewrfcas** [comment]
The released model uses features from layer8.
