### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by rose-jinyang** [ewrfcas/MAE-FAR#7]
Hello
How are you?
Thanks for contributing to this project.
I am going to train a model with your method on my custom dataset.
Should I pre-train MAE model on my custom dataset?
Otherwise, can we reuse the pre-trained model on Places2 dataset?

**Comment by ewrfcas** [comment]
I think reusing the pre-trained model on Places2 can work well in most scenes. For human faces, we recommend to use the MAE pretrained on FFHQ.

**Comment by rose-jinyang** [comment]
Thanks

**Comment by rose-jinyang** [comment]
Hello
I trained MAE and ACR models on my custom dataset.
I got the last checkpoint file at "ckpts/cart/version_0/checkpoints/epoch=99-step=125000.ckpt".
I am going to finetune this last checkpoint.
But After loaded this checkpoint, the finetuning script is exited.
What do u think about the reason?

**Comment by rose-jinyang** [comment]
Oh, I think that there is a problem in setting of total_step.

![image](https://user-images.githubusercontent.com/47862419/218358895-a1366354-8c40-4d4f-8f93-2321668fff1d.png)

I think that the total_step value in finetuning should be greater than ACR training step.

**Comment by rose-jinyang** [comment]
One more question
Why is the "input_size" value 256 in config for finetuning?
The ONLY "eval_size" is 512.

**Comment by ewrfcas** [comment]
Yes, you should adjust the total step for the fine-tuning.
The most important arg is ```dynamic_size=True``` for the fine-tuning with dynamic resolution from 256 to 512. 
And we just want to know the performance of 512 during the finetuning.

**Comment by rose-jinyang** [comment]
If so, I think that dynamic_size=True should be mentioned in the README of this repo.

![image](https://user-images.githubusercontent.com/47862419/218369546-6b90060a-0021-4925-81bf-7488f02104b1.png)

**Comment by ewrfcas** [comment]
Oh, thanks, I revised it.
