### ISSUE TITLE
Questions of the validation step

### ISSUE THREAD

**Issue by yqjiang6** [ewrfcas/MAE-FAR#8]
Hi! 
    Thanks for your impressive work! I'm trying to run your code with two GPUS, but I found that during the validation step, the results  saved in "ckpts/exp_name/validation" only have half numbers of the images, which will then lead to the assertion error in "get_inpainting_metrics" function. Could you please help me solve this problem?
Thank you!

**Comment by yqjiang6** [comment]
I tried with single GPU and this does not happen, so I think maybe this is error is due to ddp?

**Comment by ewrfcas** [comment]
Maybe it is caused by the function ```validation_step``` is only worked in rank=0 during the DDP.
But this phenomenon does not happen in my pytorch_lightning (1.2.9).

**Comment by yqjiang6** [comment]
Thanks for your reply! It's indeed the problem of pytorch-lightning. I switch its version from 1.5.0 to 1.2.9 and fix this problem.
