### ISSUE TITLE
Inference on high-resolution images.

### ISSUE THREAD

**Issue by rose-jinyang** [ewrfcas/MAE-FAR#9]
Hello
How are you?
Thanks for contributing to this project.
Could u provide a inference script for high-resolution (ex: 2040x1920) images with your 512x512 model?
If it is impossible, should we train a model with high-resolution images again?

**Comment by ewrfcas** [comment]
Trying to change ```eval_size``` in config from 512 to 2040 should address this problem.
Re-training is not very necessary, but retraining in higher resolution should improve performance.
